Repository ismrm-iberian/ismrm-iberian.github.io, pull requests merged in 2021-03, with the labels that each got.

#7 Update navbar
  _includes/header.html
  about.md
  jobs.md
  mriberians.md
Labels: content

#8 Update footer
  _includes/footer.html
  _includes/header.html
  about.md
Labels: content

#9 Add lorem ipsum and changes to main page
  _includes/footer.html
  _includes/header.html
  _includes/postbox.html
  _includes/sidebar.html
  about.md
  index.html
  jobs.md
  mriberians.md
Labels: content

#10 Add social media and other edits
  README.md
  _includes/beforefooter.html
  _includes/footer.html
  _layouts/default.html
  index.html
Labels: content

#11 Bug fix
  _layouts/default.html
Labels: fix

#12 Bug fix (for real this time)
  _layouts/default.html
Labels: fix

#13 Changed button colors
  assets/css/custom.scss
Labels: css

#14 Fix buttons
  assets/css/custom.scss
Labels: fix

#15 Fix what wasn't fixed
  assets/css/custom.scss
Labels: fix

#16 More fixes to buttons
  assets/css/custom.scss
Labels: fix

#17 Hopefully final fixes to buttons
  assets/css/custom.scss
Labels: fix

#18 Removed button borders on hover
  assets/css/custom.scss
Labels: css

#19 Edited last part of footer
  _includes/footer.html
Labels: content

#20 Fix link
  _includes/footer.html
Labels: fix

#21 Include more words in link
  _includes/footer.html
Labels: content

#22 Changed main button and newsletter text
  _includes/newsletter.html
  index.html
Labels: content

#23 Fix typo
  _includes/newsletter.html
Labels: fix

#24 Update sidebar content
  _includes/sidebar.html
Labels: content

#25 Fix typo
  _includes/sidebar.html
Labels: fix

#26 Add some links
  _includes/beforefooter.html
  _includes/footer.html
  _includes/header.html
  _includes/sidebar.html
Labels: content

#27 add bylaws.md
  bylaws.md
Labels: content

#30 Add amigo iberico
  _includes/sidebar.html
  amigo_iberico.md
  assets/images/Iberian_amigo.png
Labels: content

#32 Rescue post section and add twitter timeline
  index.html
Labels: content, structure

#33 Resized twitter timeline
  index.html
Labels: fix

#34 Rescued author in post card
  _includes/postbox.html
  index.html
Labels: structure

#35 Rescued pagination and authors on config
  _config.yml
Labels: structure

#36 Add shadow and rounded borders to cards
  assets/css/custom.scss
Labels: css

#37 Made border radius important
  assets/css/custom.scss
Labels: css

#38 Made lines darker
  assets/css/custom.scss
Labels: css

#39 Fix color
  assets/css/custom.scss
Labels: fix

#40 Fix color
  assets/css/custom.scss
Labels: fix

#41 Rescued authors for featured
  _includes/featuredbox.html
Labels: structure

#42 Added border to twitter timeline
  index.html
Labels: css

#43 Reduce padding for twitter box and change color to twitter blue
  assets/css/custom.scss
Labels: css

#44 Add changes to twitter style on index and make font bigger
  assets/css/custom.scss
  index.html
Labels: css

#49 Update banner and committee images.
  assets/css/custom.scss
  assets/images/.DS_Store
  assets/images/Ambassadors.png
  assets/images/Banner2.png
  assets/images/ExecutiveCommittee.png
  assets/images/banner5_blue.png
  assets/images/banner6_blue_rect.png
  assets/images/banner7_v2_blue.png
  committee.md
  community_news.md
  iberians_around_world.md
Labels: content, css

#50 Add job board
  jobs.md
Labels: content

#51 Edited job board style
  assets/css/custom.scss
  jobs.md
Labels: css

#52 Removed useful part, moved tweets up, and added sponsor us button
  _includes/sidebar.html
  index.html
Labels: content

#53 Fix errors in sponsors sidebar
  index.html
Labels: fix

#54 Made committee member images smaller
  assets/css/custom.scss
  committee.md
Labels: css

#55 Improve sponsors sidebar
  assets/css/custom.scss
  index.html
Labels: css

#58 Update banner
  assets/css/custom.scss
  assets/images/banner7_v2_blue.png
  assets/images/banner_7_v3_blue.png
Labels: css

#59 Update post with link to Twitter and remove template posts
  _posts/2018-01-12-is-intelligence-enough.md
  _posts/2018-01-12-powerful-things-markdown-editor.md
  _posts/2018-01-12-red-riding.md
  _posts/2018-01-12-tree-of-codes.md
  _posts/2018-01-12-we-all-wait-for-summer.md
  _posts/2021-03-29-annual_meeting.md
Labels: content
