Repository ismrm-iberian/ismrm-iberian.github.io, pull requests merged in 2021-04, with the labels that each got.

#60 Add PG meeting post
  _posts/2021-04-05-pg_meeting.md
  assets/images/ana_laura.png
  assets/images/pg_conference_logo.png
  assets/images/pg_meeting_2021_programme_at_glance.png
Labels: content

#64 Add timeline post
  _posts/2021-04-05-timeline_2021.md
  assets/images/timeline_2021.png
Labels: content

#65 Update 2021-03-29-annual_meeting.md
  _posts/2021-03-29-annual_meeting.md
Labels: content

#67 Update banner
  assets/css/custom.scss
  assets/images/banner_7_v3_blue.png
  assets/images/banner_7_v4_blue.png
Labels: css

#75 Update 2021-03-29-annual_meeting.md
  _posts/2021-03-29-annual_meeting.md
Labels: content

#78 Create 2021-04-28-website_tour.md
  _posts/2021-04-28-website_tour.md
Labels: posts

#79 Add post image
  assets/images/website.png
Labels: posts

#82 Bug fix pull request #81
  assets/css/custom.scss
Labels: fix

#76 Create 28_04_pgmeeting.md
  _posts/28_04_pgmeeting.md
Labels: posts

#84 Add collage
  assets/images/pgmeeting_collage.png
Labels: content

#85 Rename PG meeting recap post filename
  _posts/2021-04-28-pgmeeting.md
Labels: fix

#86 Add Rita as author
  _config.yml
  assets/images/.DS_Store
Labels: content

#83 Improving Committee page layout
  assets/css/custom.scss
Labels: css

#87 Fix local build and compatibility with GitHub Pages
  .gitignore
  README.md
  _config.yml
Labels: fix, structure

#88 Format HTML, JS and CSS files
  .editorconfig
  _includes/beforefooter.html
  _includes/disqus.html
  _includes/featuredbox.html
  _includes/footer.html
  _includes/head.html
  _includes/header.html
  _includes/newsletter.html
  _includes/pagination.html
  _includes/postbox.html
  _includes/sidebar.html
  _layouts/archive.html
  _layouts/default.html
  _layouts/page.html
  _layouts/post-right-sidebar.html
  assets/css/custom.scss
  assets/css/theme.css
  assets/js/ie10-viewport-bug-workaround.js
  assets/js/theme.js
  contact.html
  index.html
Labels: structure

#89 Fix from baseurl to relative_url
  _config.yml
  _includes/beforefooter.html
  _includes/featuredbox.html
  _includes/footer.html
  _includes/head.html
  _includes/header.html
  _includes/pagination.html
Labels: enhancement, fix
